### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Selians** [Selians/Simps-In-Development#11]
Random crash when playing ingame. Seems to be caused by a ticking entity; but no mods have been changed/added which affect entities

**Comment by IHVD** [comment]
post crash log xx

**Comment by Selians** [comment]
[crash-2022-08-02_21.01.23-client.txt](https://github.com/Selians/Simps-In-Development/files/9245372/crash-2022-08-02_21.01.23-client.txt)

**Comment by Selians** [comment]
[crash-2022-07-31_20.42.52-client.txt](https://github.com/Selians/Simps-In-Development/files/9245647/crash-2022-07-31_20.42.52-client.txt)
[crash-2022-07-31_20.36.01-client.txt](https://github.com/Selians/Simps-In-Development/files/9245648/crash-2022-07-31_20.36.01-client.txt)

**Comment by Selians** [comment]
Caused by Eldritch Mobs - Removed for now
https://github.com/HyperPigeon/Eldritch-Mobs/issues
https://github.com/HyperPigeon/Eldritch-Mobs/issues/43
